# Generated by Django 6.0.4 on 2026-04-12 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_species_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High')], db_index=True, default='LO', max_length=2)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='species',
            name='core_specie_categor_cc9f7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='species',
            name='core_specie_common__7e654c_idx',
        ),
        migrations.RemoveIndex(
            model_name='species',
            name='core_specie_scienti_4fed3f_idx',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='flagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flagged_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.observation'),
        ),
    ]
