# Generated by Django 5.2.13 on 2026-04-09 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('nt_classification', models.CharField(choices=[('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable')], db_index=True, max_length=2)),
                ('epbc_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('introduced_status', models.CharField(blank=True, max_length=80, null=True)),
                ('order_name', models.CharField(blank=True, max_length=120, null=True)),
                ('family', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['category', 'common_name', 'scientific_name'],
                'indexes': [models.Index(fields=['category', 'nt_classification'], name='core_specie_categor_cc9f7e_idx'), models.Index(fields=['common_name'], name='core_specie_common__7e654c_idx'), models.Index(fields=['scientific_name'], name='core_specie_scienti_4fed3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to='observations/audio/%Y/%m/')),
                ('location', models.CharField(max_length=200)),
                ('confidence_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, default='')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.species')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
