# Generated by Django 5.2.13 on 2026-04-16 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anomaly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
