# Generated by Django 5.2.13 on 2026-04-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['category', 'common_name', 'scientific_name'], 'verbose_name_plural': 'Species'},
        ),
    ]
